// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the frontend-bound Wails service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Greet returns a greeting for the given name.
 */
export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(2659711170, name);
}
